remote_theme: pages-themes/time-machine@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Mansi Gahlot
description: [ Data Analyst | HR Analytics | Skilled in SQL, Python, and Power BI | Transforming recruitment and workforce data into actionable insights]
